export const Items = [
  {
    id: 1,
    image: '/./images/Items/wireless_earbuds.jpg',
    name: 'Wireless Earbuds, IPX8',
    price: 89,
    info: 'Lorem ipsum dolor sit amet.',
    rating: 4.6,
    review: 78,
    type: 'true wireless',
    color: 'black',
    brand: 'IPX8',
    discount: '20',
    microphonepresent: 'yesyes',
    offers: 'buy more save more',
    compaitaiblewith: 'all',
    category: 'audio & video'
  }, {
    id: 2,
    image: '/./images/Items/airpods_pink.jpg',
    name: 'AirPods Max',
    price: 559,
    info: 'Lorem ipsum dolor sit amet.',
    rating: 5,
    review: 121,
    type: 'true wireless',
    color: 'pink',
    brand: 'Apple',
    discount: '',
    microphonepresent: 'yes',
    offers: 'no cost EMI',
    compaitaiblewith: 'laptop mobile desktop',
    category: 'audio & video',
    color1: '/./images/airpods_green.jpg',
    color2: '/./images/airpods_black.webp',
    color3: '/./images/airpods_blue.jpg',
    color4: '/./images/airpods_white.webp'
  }, {
    id: 3,
    image: '/./images/Items/bose.webp',
    name: 'Bose BT Earphones',
    price: 289,
    info: 'Lorem ipsum dolor sit amet.',
    rating: 4.2,
    review: 88,
    type: 'wired & wireless',
    color: 'black',
    brand: 'Boat',
    discount: '25',
    microphonepresent: 'yes',
    offers: 'speical price',
    compaitaiblewith: '',
    category: 'audio & video'
  }, {
    id: 4,
    image: '/./images/Items/vivefox.webp',
    name: 'VEVEFOX Headphones',
    price: 39,
    info: 'Lorem ipsum dolor sit amet.',
    rating: 4.3,
    review: 90,
    type: 'wired & wireless',
    color: 'red',
    brand: 'VEVEFOX',
    discount: '',
    microphonepresent: 'yes',
    offers: 'no cost EMI',
    compaitaiblewith: 'audio player',
    category: 'audio & video'
  }, {
    id: 5,
    image: '/./images/Items/jbl.webp',
    name: 'JBL TUNE 60CB TNC',
    price: 59,
    info: 'Lorem ipsum dolor sit amet.',
    rating: 3.7,
    review: 34,
    type: 'wireless',
    color: 'black',
    brand: 'Boat',
    discount: '30',
    microphonepresent: 'yes',
    offers: 'buy more save more',
    compaitaiblewith: 'desktop',
    category: 'audio & video'
  }
]